# Workflow Name
name: CI

# Define when to trigger the workflow
on:
  push: # The event that occurs
    branches:
        - main
jobs:
    test-and-build:
        runs-on: ubuntu-latest

        # Define steps to execute
        steps:
          - name: Check out the code # This checks out the GitHub repository
            uses: actions/checkout@v3

          - name: Install Chromium browser
            run: sudo apt-get install -y chromium-browser

          - name: Install dependencies
            run: sudo apt-get install -y npm

          - name: Run QUnit tests
            run: |
              npx qunit --browser chromium index.html

          - name: Install the Docker Engine
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}

          - name: Build the Docker Image
            env:
              image_name: new-image
              version: 1.0.0
              username: ${{ secrets.DOCKER_USERNAME }}
            run: |
                docker build -t $username/$image_name:$version .

          - name: Push the Docker image to Docker Hub
            env:
              image_name: new-image
              version: 1.0.0
              username: ${{ secrets.DOCKER_USERNAME }}
            run: |
                docker push $username/$image_name:$version
          - name: Run tests inside Docker container
            run: |
               docker run --rm ${{ secrets.DOCKER_USERNAME }}/new-image:1.0.0 /home/adetutu/designo-website/src/test.js

              
              

          


      
   
