name: CI

on:
  push:
    branches:
      - master

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Install Nginx
        run: |
          sudo apt-get update
          sudo apt-get install -y nginx
          sudo systemctl start nginx
          sudo systemctl enable nginx

      - name: Copy files to Nginx's root directory
        run: |
          sudo chmod -R 777 /var/www
          sudo chown -R $USER:$USER /var/www
          sudo rm -rf /var/www/html
          sudo mkdir /var/www/html
          sudo cp -r * /var/www/html
          sudo systemctl restart nginx
          sleep 5

      - name: Check if app is accessible using curl
        run: |
          curl -f http://localhost:80/index.html > result.log || echo "App not accessible" > result.log

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: result.log

      # Step 6: Install Docker Engine
      - name: Install Docker Engine
        uses: docker/setup-buildx-action@v2
        with:
          version: 'latest'

      # Step 7: Log in to Docker Hub
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 8: Build the Docker image
      - name: Build the Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/new-image:1.0.0 .

      # Step 9: Scan the Docker image for vulnerabilities
      - name: Scan the Docker image for vulnerabilities
        uses: anchore/scan-action@v3
        id: scan
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/new-image:1.0.0
          severity-cutoff: medium
          fail-build: true
          output-format: sarif  # Generate SARIF report

      # Step 10: Upload the vulnerability scan report as an artifact
      - name: Upload Anchore Scan Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: anchore-scan-report
          path: ${{ steps.scan.outputs.report }}  # Path to the generated SARIF report
          
      # Step 11: Push the Docker image to Docker Hub
      - name: Push the Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/new-image:1.0.0
