name: CI

# Define when to trigger the workflow
on:
  push:
    branches:
      - master

jobs:
  print-greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Print Greeting
        run: echo "Hello world"

      - name: Create directory and file
        run: |
          #!/bin/bash
          mkdir user
          cd user
          touch name.txt
          echo "Hello World!" > name.txt

