name: CI

# Define when to trigger the workflow
on:
  push:
    branches:
      - master

jobs:
  print-greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Print Greeting
        run: echo "Hello world"

      - name: Create directory and file
        run: |
          mkdir user
          cd user
          touch name.txt
          echo "Hello World!" > name.txt

      - name: Install Docker Engine
        uses: docker/login-action@v3
        with:

          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: login docker hube
        run: echo  ${{ secrets.DOCKER_TOKEN }}   

      - name: Build the Docker image
        env:
          image_name: Test-image
          version: 1.0.0
          username: ${{ secrets.DOCKER_USERNAME }}
        run: |
          docker build -t $username/$image_name:$version .
